### ISSUE TITLE
'ktest' error

### ISSUE THREAD

**Issue by vikas-sharma-genomics** [Matteopaluh/KEMET#12]
While running this program, getting the following error:
python kemet.py genomes/test.fna -a eggnog --skip_hmm --skip_gsmm
Traceback (most recent call last):
File "./kemet.py", line 2450, in <module>
if ktest in sorted(os.listdir()):
NameError: name 'ktest' is not defined

**Comment by Matteopaluh** [comment]
Dear Vikas,
Thanks for using the KEMET tool.

Answering to your issue would probably require some more info on the execution of KEMET.
I'd suggest to check the related issue #9, in which the problem was solved by matching the FASTA and annotations file names (not the extension, of course).

Feel free to reopen and further reach for help once this approach has been tried.

Best,
Matteo
